### ISSUE TITLE
[nuxt] Nuxt-i18n integration with lazy mode does not build

### ISSUE THREAD

**Issue by KennyDurand** [ZachJW34/nx-plus#125]
Hello there,

First, thanks for your work on this library, I discovered it yesterday and it looks very promising.

I am trying to migrate one of my Nuxt projects to Nx thanks to the plugin, and there is one last error that I can't get rid of. I would be happy to help solving it but I'm not really able to understand alone what would be the best way.

## Steps to Reproduce
1. Generate a fresh app with `nx g @nx-plus/nuxt:app my-app`
2. Install nuxt-i18n : `npm i nuxt-i18n --save`
3. Add nuxt-i18n to the nuxt.config.ts :  `modules: ['nuxt-i18n'],`
4. Create a `./locales/en/index.ts` file in the Nuxt app with content: `export default {}`
5. Configure lazy mode for nuxt-i18n in nuxt.config.ts:
```
i18n: {
    locales: [
      {
        code: 'en',
        file: 'en/index.ts'
      }
    ],
    defaultLocale: 'en',
    lazy: true,
    langDir: 'locales/',
    strategy: 'no_prefix'
  },
```
6. Attempt to serve the application: `nx serve my-app`

## Current Behavior
Using nuxt-i18n inside the Nuxt application with lazy mode triggers an error that prevents compilation:
```
 ERROR  Failed to compile with 1 errors

This dependency was not found:          

* ~/lang in ./dist/apps/my-app/nuxt-i18n/utils.js
To install it, you can run: npm install --save ~/lang
```

## Expected Behavior
The project compiles without any problem.

### Environment

Plugin name and version: @nx-plus/nuxt v10.2.0

nx report:
```
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.4.4
  @nrwl/cypress : 10.4.4
  @nrwl/eslint-plugin-nx : 10.4.4
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.4
  @nrwl/linter : 10.4.4
  @nrwl/nest : 10.4.4
  @nrwl/next : Not Found
  @nrwl/node : 10.4.4
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.4
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.4
  typescript : 4.0.5
```

Thanks for your help!

**Comment by BuckyMaler** [comment]
Thanks for reporting this and for providing good details. It seems the issue is that `nuxt-i18n` is dependent on the `~` being configured as an alias with webpack, which is fair since Nuxt does configure that. We remove that alias and others [here](https://github.com/ZachJW34/nx-plus/blob/master/libs/nuxt/src/webpack.ts#L6). The reason it's removed is because we want the `tsconfig.base.json` to serve as the source of truth for all aliases. Why that's important is explained in more depth [here](https://github.com/vuejs/vue-cli/issues/3123#issue-390532313). That being said, I don't think it's problematic to include the aliases provided by Nuxt.

It'd be appreciated if you opened a PR removing our deletion of the aliases provided by Nuxt. FYI, you can reproduce the error using a [playground](https://github.com/ZachJW34/nx-plus/blob/master/CONTRIBUTING.md#testing-your-changes) and test your changes there as well.

**Comment by KennyDurand** [comment]
Hi @BuckyMaler!

Thanks for your comment and sorry for late reply, I had a lot going on in my projects recently.
I created PR #158. Unit and E2E tests were passing in local environment.

However, I am not 100% sure how to test these modifications on my nx workspace. I launched `yarn create-playground` but I'm not sure how to use this playground to serve my applications. Is it supposed to bind this new playground automatically for my workspaces?

Thanks a lot for your help!

**Comment by KennyDurand** [comment]
Hey @BuckyMaler, have you had the opportunity to look at my PR? I am available to test it further and make additional modifications if needed.

**Comment by BuckyMaler** [comment]
@KennyDurand I requested a small change. Please make that at your convenience.

The playground doesn't link to other workspaces. It provides a new workspace with all of our plugins installed so that you can test your changes. I tested by changing my working directory to `tmp/nx-playground/proj`, generated a Nuxt app, and added `nuxt-i18n`.
