### ISSUE TITLE
Folder structure with Nx and Nuxt

### ISSUE THREAD

**Issue by kasszz** [ZachJW34/nx-plus#159]
As a prefix I want to say sorry if I'm not using the correct channel for this question. Now the actual discussion:

**The folder structure with Nx and Nuxt**

I have a hard time wrapping my head around the idea of Nx in context with Nuxt.
Do you guys (non-gender) have any tips and/or tricks for me. Maybe an example or two?

**Explanation**
This is the reason why I'm asking this:
Nuxt itself has a system where it imports all pages and generate a routing system from that. But Nx says that 99% of your code should be in libs. So do you have a libs/<app-name>/pages/ folder with all the pages and manually create the routing system in the app.

**Comment by ZachJW34** [comment]
I would say that you would have all your pages inside of the generated app so that Nuxt can generate all of its routes normally. These pages would act more like container components, and any of the components can then live inside of libraries if you want to put them there. Personally, I wouldn't deviate too far away from what Nuxt recommends because you'll wind up in a place where, as you said, you'll have to manually configure things rather than letting Nuxt handle it.
I'm by no means a Nuxt expert, so I'd welcome any other opinions on this topic.

**Comment by kasszz** [comment]
Okay :) thanks for answering, maybe it's a bit too generic but it almost feels like the apps are things that you want to test with e2e testing, and the libs stuff is unit based. So pages, are like you said, more configs of a route, and contain no logic, and all the logic (that need to be tested by unit tests) live in the libs folder.

**Comment by kasszz** [comment]
Another question about that, what do you do with the assests? Those are optimised by Nuxt. But I find it weird to have the components look to the app for the assets

**Comment by ZachJW34** [comment]
I think the best advice I could give you is to follow what Nx recommends for Next since they are both similar frameworks.
