### ISSUE TITLE
Build same library for both vue2 and vue3

### ISSUE THREAD

**Issue by pareshchouhan** [ZachJW34/nx-plus#205]
## Description
Build library for both Vue2 and Vue3 without having separate projects in a NX repo

## Motivation
Most old projects are using Vue2

## Suggested Implementation
Have separate build files, We have done it before with different rollup configs before
Vue2 build script https://gist.github.com/pareshchouhan/af1a577ca092ffa8705534ca78911635
Vue3 build script https://gist.github.com/pareshchouhan/040b36a287dd7ababb385a0dbea06084
package.json https://gist.github.com/pareshchouhan/e12b02c72e349f689a529dc030123508  

Commands could be made like these  

```sh
nx build project-name:vue2
nx build project-name:vue3
```

**Comment by pareshchouhan** [comment]
Update on this, now there's a package that allows to build for both vue2 and vue3, It is called `vue-demi` any plans to include it in the newer versions of nx-plus vue?
https://github.com/vueuse/vue-demi

**Comment by ZachJW34** [comment]
We use `@vue/cli` to build and serve the apps and libs created with `@nx-plus/vue`. I'm not sure if `@vue/cli` supports both vue 2 and vue 3 builds, though I suppose if you swapped out all the vue 3 APIs with their corresponding `vue-demi` equivalents it might work. I don't think this is something we are going to support since Vue 3 is stable, so writing a custom builder for your project might be the way to go so you can have full control over the bundler.
